Release alt
Krzysztow/modbus-utils pull request #10
Opened 2021-08-11 10:14 UTC by AlexSP0

This is .spec file to build rpm package for ALT Linux.

2021-08-16 11:29 UTC, NIR-Ginko requested changes

2021-08-16 11:29 UTC, NIR-Ginko commented on .gear/modbus-utils.spec
> +BuildRequires(pre): rpm-macros-cmake
Please move these directives lower, before `BuildRequires`.

2021-08-23 14:05 UTC, AlexSP0 commented on .gear/modbus-utils.spec
> +BuildRequires(pre): rpm-macros-cmake
Fixed!

2021-08-23 14:10 UTC, NIR-Ginko commented
Ping @Krzysztow . Please review and accept the patch if possible. We have tested the build on ALT Workstation 9 and it works fine. We are willing to package the software for ALT Linux and this is our build system instructions which may be also used by other distributions.

2021-08-23 20:11 UTC, Krzysztow commented
Hi, sorry for delays. I'm pretty overwhelmed with things going o. Thanks for contribution.

2021-08-23 20:12 UTC, merged